import sqlite3 as sql
conn  = sql.connect('class_schedule_4.db')
c = conn.cursor()


c.execute("""create table room (RNumber text PRIMARY KEY, RoomType text, Capacity integer)""")
c.execute("insert into room Values ('C301', 'Classroom', 50),"
                                  "('C302', 'Classroom', 50),"
                                  "('C303', 'Classroom', 50),"
                                  "('C304', 'Classroom', 50),"
                                  "('C305', 'Classroom', 50),"
                                  "('C306', 'Classroom', 50),"
                                  "('C307', 'Classroom', 50),"
                                  "('C308', 'Classroom', 50),"
                                  "('C309', 'Classroom', 50),"
                                  "('C310', 'Classroom', 50),"
                                  "('C311', 'Classroom', 50),"
                                  "('C312', 'Classroom', 50),"
                                  "('C313', 'Classroom', 50),"
                                  "('C314', 'Classroom', 50),"
                                  "('C315', 'Classroom', 50),"
                                  "('C316', 'Classroom', 50),"
                                  "('C317', 'Classroom', 50),"
                                  "('Margala 1', 'Lab', 50),"
                                  "('Karakoram', 'Lab', 50),"
                                  "('Margala 3', 'Lab', 50),"
                                  "('Margala 4', 'Lab', 50),"
                                  "('Rohtas ', 'Lab', 50),"
                                  "('Rawal 1', 'Lab', 50),"
                                  "('Khyber 3', 'Lab', 50),"
                                  "('DLD 1', 'Lab', 50),"
                                  "('DLD 2', 'Lab', 50)")


c.execute("""create table meeting_time (MeetingTimeID text PRIMARY KEY, Time text, Checker int, Matcher int)""")
c.execute("insert into meeting_time Values ('MT1', 'Mon, Wed, Fri 09:00 - 10:00', 0, 1),"
                                          "('MT2', 'Mon, Wed, Fri 10:00 - 11:00', 0, 2),"
                                          "('MT3', 'Mon, Wed, Fri 11:00 - 12:00', 0, 3),"
                                          "('MT4', 'Mon, Wed, Fri 12:00 - 01:00', 0, 4),"
                                          "('MT5', 'Mon, Wed, Fri 01:00 - 02:00', 0, 5),"
                                          "('MT6', 'Mon, Wed, Fri 02:00 - 03:00', 0, 6),"
                                          "('MT7', 'Mon, Wed, Fri 03:00 - 04:00', 0, 7),"
                                          "('MT8', 'Mon, Wed, Fri 04:00 - 05:00', 0, 8),"
                                          "('MT9', 'Mon, Wed, Fri 05:00 - 06:00', 0, 9),"
                                          "('MT10', 'Tue, Wed, Thurs 09:00 - 10:00', 0, 10),"
                                          "('MT11', 'Tue, Wed, Thurs 10:00 - 11:00', 0, 11),"
                                          "('MT12', 'Tue, Wed, Thurs 11:00 - 12:00', 0, 12),"
                                          "('MT13', 'Tue, Wed, Thurs 12:00 - 01:00', 0, 13),"
                                          "('MT14', 'Tue, Wed, Thurs 01:00 - 02:00', 0, 14),"
                                          "('MT15', 'Tue, Wed, Thurs 02:00 - 03:00', 0, 15),"
                                          "('MT16', 'Tue, Wed, Thurs 03:00 - 04:00', 0, 16),"
                                          "('MT17', 'Tue, Wed, Thurs 04:00 - 05:00', 0, 17),"
                                          "('MT18', 'Tue, Wed, Thurs 05:00 - 06:00', 0, 18),"
                                          "('MT19', 'Wed, Thurs, Fri 09:00 - 10:00', 0, 19),"
                                          "('MT20', 'Wed, Thurs, Fri 10:00 - 11:00', 0, 20),"
                                          "('MT21', 'Wed, Thurs, Fri 11:00 - 12:00', 0, 21),"
                                          "('MT22', 'Wed, Thurs, Fri 12:00 - 01:00', 0, 22),"
                                          "('MT23', 'Wed, Thurs, Fri 01:00 - 02:00', 0, 23),"
                                          "('MT24', 'Wed, Thurs, Fri 02:00 - 03:00', 0, 24),"
                                          "('MT25', 'Wed, Thurs, Fri 03:00 - 04:00', 0, 25),"
                                          "('MT26', 'Wed, Thurs, Fri 04:00 - 05:00', 0, 26),"
                                          "('MT27', 'Wed, Thurs, Fri 05:00 - 06:00', 0, 27),"
                                          "('MT28', 'Mon, Tue 09:00 - 10:30', 0, 28),"
                                          "('MT29', 'Mon, Tue 10:30 - 12:00', 0, 29),"
                                          "('MT30', 'Mon, Tue 12:00 - 01:30', 0, 30),"
                                          "('MT31', 'Mon, Tue 01:30 - 03:00', 0, 31),"
                                          "('MT32', 'Mon, Tue 03:00 - 04:30', 0, 32),"
                                          "('MT33', 'Mon, Tue 04:30 - 06:00', 0, 33),"
                                          "('MT34', 'Tue, Wed 09:00 - 10:30', 0, 34),"
                                          "('MT35', 'Tue, Wed 10:30 - 12:00', 0, 35),"
                                          "('MT36', 'Tue, Wed 12:00 - 01:30', 0, 36),"
                                          "('MT37', 'Tue, Wed 01:30 - 03:00', 0, 37),"
                                          "('MT38', 'Tue, Wed 03:00 - 04:30', 0, 38),"
                                          "('MT39', 'Tue, Wed 04:30 - 06:00', 0, 39),"
                                          "('MT40', 'Tue, Thurs 09:00 - 10:30', 0, 40),"
                                          "('MT41', 'Tue, Thurs 10:30 - 12:00', 0, 41),"
                                          "('MT42', 'Tue, Thurs 12:00 - 01:30', 0, 42),"
                                          "('MT43', 'Tue, Thurs 01:30 - 03:00', 0, 43),"
                                          "('MT44', 'Tue, Thurs 03:00 - 04:30', 0, 44),"
                                          "('MT45', 'Tue, Thurs 04:30 - 06:00', 0, 45),"
                                          "('MT46', 'Mon, Fri 09:00 - 10:30', 0, 46),"
                                          "('MT47', 'Mon, Fri 10:30 - 12:00', 0, 47),"
                                          "('MT48', 'Mon, Fri 12:00 - 01:30', 0, 48),"
                                          "('MT49', 'Mon, Fri 01:30 - 03:00', 0, 49),"
                                          "('MT50', 'Mon, Fri 03:00 - 04:30', 0, 50),"
                                          "('MT51', 'Mon, Fri 04:30 - 06:00', 0, 51),"
                                          "('MT52', 'Tue, Thurs, Fri 09:00 - 10:00', 0, 52),"
                                          "('MT53', 'Tue, Thurs, Fri 10:00 - 11:00', 0, 53),"
                                          "('MT54', 'Tue, Thurs, Fri 11:00 - 12:00', 0, 54),"
                                          "('MT55', 'Tue, Thurs, Fri 12:00 - 01:00', 0, 55),"
                                          "('MT56', 'Tue, Thurs, Fri 01:00 - 02:00', 0, 56),"
                                          "('MT57', 'Tue, Thurs, Fri 02:00 - 03:00', 0, 57),"
                                          "('MT58', 'Tue, Thurs, Fri 03:00 - 04:00', 0, 58),"
                                          "('MT59', 'Tue, Thurs, Fri 04:00 - 05:00', 0, 59),"
                                          "('MT60', 'Tue, Thurs, Fri 05:00 - 06:00', 0, 60),"
                                          "('MT61', 'Mon 09:00 - 11:00', 0, 61),"
                                          "('MT62', 'Mon 11:00 - 01:00', 0, 62),"
                                          "('MT63', 'Mon 01:00 - 03:00', 0, 63),"
                                          "('MT64', 'Mon 03:00 - 05:00', 0, 64),"
                                          "('MT65', 'Tue 09:00 - 11:00', 0, 65),"
                                          "('MT66', 'Tue 11:00 - 01:00', 0, 66),"
                                          "('MT67', 'Tue 01:00 - 03:00', 0, 67),"
                                          "('MT68', 'Tue 03:00 - 05:00', 0, 68),"
                                          "('MT69', 'Wed 09:00 - 11:00', 0, 69),"
                                          "('MT70', 'Wed 11:00 - 01:00', 0, 70),"
                                          "('MT71', 'Wed 01:00 - 03:00', 0, 71),"
                                          "('MT72', 'Wed 03:00 - 05:00', 0, 72),"
                                          "('MT73', 'Thu 09:00 - 11:00', 0, 73),"
                                          "('MT74', 'Thu 11:00 - 01:00', 0, 74),"
                                          "('MT75', 'Thu 01:00 - 03:00', 0, 75),"
                                          "('MT76', 'Thu 03:00 - 05:00', 0, 76),"
                                          "('MT77', 'Fri 09:00 - 11:00', 0, 77),"
                                          "('MT78', 'Fri 11:00 - 01:00', 0, 78),"
                                          "('MT79', 'Fri 01:00 - 03:00', 0, 79),"
                                          "('MT80', 'Fri 03:00 - 05:00', 0, 80),"
                                          "('MT81', 'Mon 09:00 - 12:00', 0, 81),"
                                          "('MT82', 'Mon 12:00 - 03:00', 0, 82),"
                                          "('MT83', 'Mon 03:00 - 06:00', 0, 83),"
                                          "('MT84', 'Tue 09:00 - 12:00', 0, 84),"
                                          "('MT85', 'Tue 12:00 - 03:00', 0, 85),"
                                          "('MT86', 'Tue 03:00 - 06:00', 0, 86),"
                                          "('MT87', 'Wed 09:00 - 12:00', 0, 87),"
                                          "('MT88', 'Wed 12:00 - 03:00', 0, 88),"
                                          "('MT89', 'Wed 03:00 - 06:00', 0, 89),"
                                          "('MT90', 'Thu 09:00 - 12:00', 0, 90),"
                                          "('MT91', 'Thu 12:00 - 03:00', 0, 91),"
                                          "('MT92', 'Thu 03:00 - 06:00', 0, 92),"
                                          "('MT93', 'Fri 09:00 - 12:00', 0, 93),"
                                          "('MT94', 'Fri 12:00 - 03:00', 0, 94),"
                                          "('MT95', 'Fri 03:00 - 06:00', 0, 95),"
                                          "('MT96', 'Mon, Thurs, Fri 09:00 - 10:00', 0, 96),"
                                          "('MT97', 'Mon, Thurs, Fri 10:00 - 11:00', 0, 97),"
                                          "('MT98', 'Mon, Thurs, Fri 11:00 - 12:00', 0, 98),"
                                          "('MT99', 'Mon, Thurs, Fri 12:00 - 01:00', 0, 99),"
                                          "('MT100', 'Mon, Thurs, Fri 01:00 - 02:00', 0, 100),"
                                          "('MT101', 'Mon, Thurs, Fri 02:00 - 03:00', 0, 101),"
                                          "('MT102', 'Mon, Thurs, Fri 03:00 - 04:00', 0, 102),"
                                          "('MT103', 'Mon, Thurs, Fri 04:00 - 05:00', 0, 103),"
                                          "('MT104', 'Mon, Thurs, Fri 05:00 - 06:00', 0, 104),"
                                          "('MT105', 'Wed, Thurs 09:00 - 10:30', 0, 105),"
                                          "('MT106', 'Wed, Thurs 10:30 - 12:00', 0, 106),"
                                          "('MT107', 'Wed, Thurs 12:00 - 01:30', 0, 107),"
                                          "('MT108', 'Wed, Thurs 01:30 - 03:00', 0, 108),"
                                          "('MT109', 'Wed, Thurs 03:00 - 04:30', 0, 109),"
                                          "('MT110', 'Wed, Thurs 04:30 - 06:00', 0, 110),"
                                          "('MT111', 'Mon 09:00 - 11:00, Tue 09:00 - 10:00', 0, 111),"
                                          "('MT112', 'Mon 11:00 - 01:00, Tue 11:00 - 12:00', 0, 112),"
                                          "('MT113', 'Mon 01:00 - 03:00, Tue 01:00 - 02:00', 0, 113),"
                                          "('MT114', 'Mon 03:00 - 05:00, Tue 03:00 - 04:00', 0, 114),"
                                          "('MT115', 'Mon 09:00 - 11:00, Wed 09:00 - 10:00', 0, 115),"
                                          "('MT116', 'Mon 11:00 - 01:00, Wed 11:00 - 12:00', 0, 116),"
                                          "('MT117', 'Mon 01:00 - 03:00, Wed 01:00 - 02:00', 0, 117),"
                                          "('MT118', 'Mon 03:00 - 05:00, Wed 03:00 - 04:00', 0, 118),"
                                          "('MT119', 'Wed 09:00 - 11:00, Fri 09:00 - 11:00', 0, 119),"
                                          "('MT120', 'Wed 11:00 - 01:00, Fri 09:00 - 11:00', 0, 120),"
                                          "('MT121', 'Wed 01:00 - 03:00, Fri 09:00 - 11:00', 0, 121),"
                                          "('MT122', 'Wed 03:00 - 05:00, Fri 09:00 - 11:00', 0, 122),"
                                          "('MT123', 'Mon, Tue, Wed 09:00 - 10:00', 0, 123),"
                                          "('MT124', 'Mon, Tue, Wed 10:00 - 11:00', 0, 124),"
                                          "('MT125', 'Mon, Tue, Wed 11:00 - 12:00', 0, 125),"
                                          "('MT126', 'Mon, Tue, Wed 12:00 - 01:00', 0, 126),"
                                          "('MT127', 'Mon, Tue, Wed 01:00 - 02:00', 0, 127),"
                                          "('MT128', 'Mon, Tue, Wed 02:00 - 03:00', 0, 128),"
                                          "('MT129', 'Mon, Tue, Wed 03:00 - 04:00', 0, 129),"
                                          "('MT130', 'Mon, Tue, Wed 04:00 - 05:00', 0, 130),"
                                          "('MT131', 'Mon, Tue, Wed 05:00 - 06:00', 0, 131)")


c.execute("""create table instructor (InstructorID integer PRIMARY KEY, Name text, Spacer int, Spacercheck int)""")
c.execute("insert into instructor Values     (1, ' Dr Asif Naeem ', 0, 0),"
                                            "(2, ' Dr Hasan Mujtaba ', 0, 0),"
                                            "(3, ' Ms Noor ul Ain ', 0, 0),"
                                            "(4, ' Mr Hassan Raza ', 0, 0),"
                                            "(5, ' Dr Naveed Ahmad ', 0, 0),"
                                            "(6, ' Mr Shams Farooq ', 1, 0),"
                                            "(7, ' Mr Saad Salman ', 0, 0),"
                                            "(8, ' Mr Jawwad Hassan ', 0, 0),"
                                            "(9, ' Mr Hassan Mustafa ', 0, 0),"
                                            "(10, ' Ms Mehreen Alam ', 0, 0),"
                                            "(11, ' Dr Ejaz Ahmed ', 0, 0),"
                                            "(12, ' Dr Asma Ahmad ', 0, 0),"
                                            "(13, ' Dr Adnan Tariq ', 1, 0),"
                                            "(14, ' Ms Sidra Khalid ', 0, 0),"
                                            "(15, ' Dr Hammad Naveed  ', 0, 0),"
                                            "(16, ' Mr Umair Arshad ', 0, 0),"
                                            "(17, ' Mr Bilal Khalid Dar  ', 1, 0),"
                                            "(18, ' Dr Irum Inayat ', 0, 0),"
                                            "(19, ' Dr Labiba Fahad  ', 0, 0),"
                                            "(20, ' Dr Hammad Majeed  ', 1, 0),"
                                            "(21, ' Mr Ahmed Nawaz  ', 0, 0),"
                                            "(22, ' Dr Shujaat Hussain  ', 0, 0),"
                                            "(23, ' Ms Uzma Bibi  ', 0, 0),"
                                            "(24, ' Dr Atif Mughees  ', 0, 0),"
                                            "(25, ' Mr Barkan Saeed  ', 0, 0),"
                                            "(26, ' Mr Sabqat Mansoor  ', 0, 0),"
                                            "(27, ' Dr Ehtishaam Zahoor  ', 0, 0),"
                                            "(28, ' Dr Muhammad Asim  ', 1, 0),"
                                            "(29, ' Dr  Affan A. Syed  ', 0, 0),"
                                            "(30, ' Dr Omer Beg  ', 0, 0),"
                                            "(31, ' Ms Saba Rasheed  ', 0, 0),"
                                            "(32, ' Dr Aqeel Shahzad  ', 0, 0),"
                                            "(33, ' Ms Sahar Arshad  ', 0, 0),"
                                            "(34, ' Ms Azka Sameen  ', 0, 0),"
                                            "(35, ' Ms Inji Akhtar  ', 0, 0),"
                                              "(36, ' Ms Madiha Umar  ', 0, 0),"
                                              "(37, ' Mr Majid Hussain  ', 0, 0),"
                                              "(38, ' Ms Huma Altaf', 0, 0),"
                                              "(39, ' Ms Yasmeen Afzal  ', 0, 0),"
                                              "(40, ' Ms Shahnila Rahim  ', 0, 0),"
                                              "(41, ' Ms Shafaq Riaz Bhatti  ', 0, 0),"
                                              "(42, ' Mr Shehreyar Rashid ', 0, 0),"
                                              "(43, ' Mr Shoaib Mehboob  ', 0, 0),"
                                              "(44, ' Ms Saba Kanwal  ', 0, 0),"
                                              "(45, ' Ms Humera Sabir', 0, 0),"
                                              "(46, ' Ms Fatima Farooq  ', 0, 0),"
                                              "(47, ' Ms Kainat Iqbal  ', 0, 0),"
                                              "(48, ' Mr Turab Ali Kazmi ', 0, 0),"
                                              "(49, ' Mr Usman Kaiser Mughal ', 0, 0),"
                                              "(50, ' Ms Ayesha Kamran ul Haq ', 0, 0),"
                                              "(51, ' Ms Mehran Khan ', 0, 0),"
                                              "(52, ' Ms Shehr Bano ', 0, 0),"
                                              "(53, ' Mr Zia ur Rehman ', 0, 0),"
                                              "(54, ' Ms Anmol Bilal ', 0, 0),"
                                              "(55, ' Mr Muhammad Usman  ', 0, 0),"
                                              "(56, ' Mr Ali Raza', 0, 0),"
                                              "(57, ' Dr Amna Basharat  ', 0, 0),"
                                              "(58, ' Dr Omer Ishaq  ', 0, 0),"
                                              "(59, ' Dr Atif Jilani  ', 0, 0),"
                                              "(60, ' Ms Amina Asif  ', 0, 0),"
                                              "(61, ' Dr Kifyat Ullah Khan  ', 0, 0),"
                                              "(62, ' Dr Uzair Khan  ', 0, 0),"
                                              "(63, ' Dr Abdul Waheed Khan  ', 0, 0),"
                                              "(64, ' Dr Kashif Munir  ', 0, 0),"
                                              "(65, ' Dr Subhan Ullah  ', 0, 0),"
                                              "(66, ' Dr Zohaib Zafar Iqbal  ', 0, 0),"
                                              "(67, ' Dr Faisal Cheema  ', 0, 0),"
                                              "(68, ' Dr Zoya Khalid  ', 0, 0),"
                                              "(69, ' Dr Farah Jabeen  ', 0, 0),"
                                              "(70, ' Mr Usman Ashraf  ', 0, 0),"
                                              "(71, ' Ms Maimona Rasool  ', 0, 0),"
                                              "(72, ' Ms Nadia Nauman  ', 0, 0),"
                                              "(73, ' Ms Gul-e-Ayesha  ', 0, 0),"
                                              "(74, ' Ms Zunera Malik  ', 0, 0),"
                                              "(75, ' Mr Shahzad Mehmood  ', 0, 0),"
                                              "(76, ' Ms Aisha Ijaz  ', 0, 0),"
                                              "(77, ' Ms Hamda Khan  ', 0, 0),"
                                              "(78, ' Ms Sarosh Shahid  ', 0, 0),"
                                              "(79, ' Mr Ameen Chilwan  ', 0, 0),"
                                              "(80, ' Dr Noreen Jamil  ', 0, 0),"
                                              "(81, ' Dr Irfan Shah  ', 0, 0),"
                                              "(82, ' Dr Arshad Islam  ', 0, 0)")


c.execute("""create table course (CourseID integer PRIMARY KEY, CourseName text, CourseType text, Section text, MaxNumOfStudents int, Tpreference int, Dpreference integer, Qpreference integer, concount, ConflictWith text, ConflictValue text, RPreference text, Teacher text)""")

c.execute("insert into course Values   (1,'OOP (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'C301', 'Dr Naveed Ahmad'),"
                                      "(2,'DLD (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'C302', 'Mr Shams Farooq'),"
                                      "(3,'OOP (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'C303', 'Dr Naveed Ahmad'),"
                                      "(4,'DLD (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Saad Salman'),"
                                      "(5,'OOP (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Jawwad Hassan'),"
                                      "(6,'DLD (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Mehreen Alam'),"
                                      "(7,'OOP (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Hassan Mustafa'),"
                                      "(8,'DLD (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Shams Farooq'),"
                                      "(9,'OOP (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Hassan Raza'),"
                                      "(10,'DLD (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Mehreen Alam'),"
                                      "(11,'DB (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Ejaz Ahmed'),"
                                      "(12,'OS (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hasan Mujtaba'),"
                                      "(13,'ALGO (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hammad Naveed'),"
                                      "(14,'MM (2-A) ', ' Elective ',' 2-A ' , 45, 1.5, 2, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Aqeel Shahzad'),"
                                      "(15,'DB (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Ejaz Ahmed'),"
                                      "(16,'OS (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hasan Mujtaba'),"
                                      "(17,'ALGO (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Umair Arshad'),"
                                      "(18,'MM (2-B) ', ' Elective ',' 2-B ' , 45, 1.5, 2, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Aqeel Shahzad'),"
                                      "(19,'DB (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Asif Naeem'),"
                                      "(20,'OS (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Adnan Tariq'),"
                                      "(21,'ALGO (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Noor ul Ain'),"
                                      "(22,'MM (2-C) ', ' Elective ',' 2-C ' , 45, 1.5, 2, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Sahar Arshad'),"
                                      "(23,'DB (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Asma Ahmad'),"
                                      "(24,'OS (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Adnan Tariq'),"
                                      "(25,'ALGO (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Noor ul Ain'),"
                                      "(26,'DB (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Asma Ahmad'),"
                                      "(27,'OS (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Sidra Khalid'),"
                                      "(28,'ALGO (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Noor ul Ain'),"
                                      "(29,'ALGO-3 (3-A) ', ' Core ',' 3-A ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Ahmed Nawaz'),"
                                      "(30,'SE (3-A) ', ' Core ',' 3-A ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Bilal Khalid Dar'),"
                                      "(31,'OB (3-A) ', ' Elective ',' 3-A ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Azka Sameen'),"
                                      "(32,'ALGO-3 (3-B) ', ' Core ',' 3-B ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Ahmed Nawaz'),"
                                      "(33,'SE (3-B) ', ' Core ',' 3-B ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Bilal Khalid Dar'),"
                                      "(34,'OB (3-B) ', ' Elective ',' 3-B ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Azka Sameen'),"
                                      "(35,'ALGO-3 (3-C) ', ' Core ',' 3-C ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hammad Majeed'),"
                                      "(36,'SE (3-C) ', ' Core ',' 3-C ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', ' Dr Labiba Fahad'),"
                                      "(37,'OB (3-C) ', ' Elective ',' 3-C ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Inji Akhtar'),"
                                      "(38,'ALGO-3 (3-D) ', ' Core ',' 3-D ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Shujaat Hussain'),"
                                      "(39,'SE (3-D) ', ' Core ',' 3-D ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Irum Inayat'),"
                                      "(40,'ALGO-3 (3-E) ', ' Core ',' 3-E ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Ahmed Nawaz'),"
                                      "(41,'SE (3-E) ', ' Core ',' 3-E ' , 45, 1, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Irum Inayat'),"
                                      "(42,'PIT (4-A) ', ' Core ',' 4-A ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Uzma Bibi'),"
                                      "(43,'PIT (4-B) ', ' Core ',' 4-B ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Uzma Bibi'),"
                                      "(44,'PIT (4-C) ', ' Core ',' 4-C ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Atif Mughees'),"
                                      "(45,'PIT (4-D) ', ' Core ',' 4-D ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Barkan Saeed'),"
                                      "(46,'PIT (4-E) ', ' Core ',' 4-E ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Sabqat Mansoor'),"
                                      "(47,'PDC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Ehtishaam Zahoor'),"
                                      "(48,'PDC (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 3, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Shujaat Hussain'),"
                                      "(49,'NSEC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Muhammad Asim'),"
                                      "(50,'NSEC (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 5, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Muhammad Asim'),"
                                      "(51,'UX (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Saba Rasheed'),"
                                      "(52,'UX (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Saba Rasheed'),"
                                      "(53,'IBC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Ehtishaam Zahoor'),"
                                      "(54,'IOT (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Adnan Tariq'),"
                                      "(55,'ST (4-A) ', ' Elective ',' 4-A' , 45, 2, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Uzma Bibi'),"
                                      "(56,'AMAD (4-A) ', ' Elective ',' 4-A' , 45, 2, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Amna Basharat'),"
                                      "(57,'DM (4-A) ', ' Elective ',' 4-AA' , 45, 2, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Omer Ishaq'),"
                                      "(91,'ADV. ALGO (5-Y1) ', ' Core ',' 5-Y1 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hammad Majeed'),"
                                      "(92,'ADV. ALGO (5-Y2) ', ' Core ',' 5-Y2 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Hammad Majeed'),"
                                      "(93,'TPL (5-Y1) ', ' Core ',' 5-Y1 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Labiba Fahad'),"
                                      "(94,'TPL (5-Y2) ', ' Core ',' 5-Y2 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Labiba Fahad'),"
                                      "(95,'ADV. CNET (5-Z) ', ' Core ',' 5-Z ' , 45, 1.5, 3, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Abdul Waheed Khan'),"
                                      "(96,'CYB. SEC (5-Z) ', ' Core ',' 5-Z ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Muhammad Asim'),"
                                      "(97,'ADV. QA SEC (5-X) ', ' Core ',' 5-X ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Uzair Khan'),"
                                      "(98,'ADV. S/W REQ ENG (5-X) ', ' Core ',' 5-X ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Irum Inayat'),"
                                      "(99,'BIG DATA (5-U1) ', ' Core ',' 5-U1 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Kifyat Ullah Khan'),"
                                      "(100,'BIG DATA (5-U2) ', ' Core ',' 5-U2 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Kifyat Ullah Khan'),"
                                      "(101,'ML DS (5-U1) ', ' Core ',' 5-U1 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Amina Asif'),"
                                      "(102,'ML DS (5-U2) ', ' Core ',' 5-U2 ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Amina Asif'),"
                                      "(103,'MBT (5-X) ', ' Core ',' 5-X ' , 45, 1.5, 3, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Zohaib Zafar Iqbal'),"
                                      "(104,'IOT SEC (5-Z) ', ' Core ',' 5-Z ' , 45, 1.5, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Subhan Ullah'),"
                                      "(105,'UXE (5-Y) ', ' Core ',' 5-Y ' , 45, 1.5, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Amna Basharat'),"
                                      "(106,'D. VIS (5-U1) ', ' Core ',' 5-U1 ' , 45, 1.5, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Faisal Cheema'),"
                                      "(107,'D. VIS (5-U2) ', ' Core ',' 5-U2 ' , 45, 1.5, 5, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Faisal Cheema'),"
                                      "(108,'BIO-INFO (5-U) ', ' Core ',' 5-U ' , 45, 1.5, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Zoya Khalid'),"
                                      "(109,'AIP (5-U) ', ' Core ',' 5-U ' , 45, 1.5, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Omer Ishaq'),"
                                      "(58,'OOP LAB (1-A) ', ' Core Lab ',' 1-A ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Madiha Umar'),"
                                      "(59,'OOP LAB (1-B) ', ' Core Lab ',' 1-B ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Majid Hussain'),"
                                      "(60,'OOP LAB (1-C1) ', ' Core Lab ',' 1-C1 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Huma Altaf'),"
                                      "(61,'OOP LAB (1-C2) ', ' Core Lab ',' 1-C2 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Huma Altaf'),"
                                      "(62,'OOP LAB (1-D1) ', ' Core Lab ',' 1-D1 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Yasmeen Afzal'),"
                                      "(63,'OOP LAB (1-D2) ', ' Core Lab ',' 1-D2 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Shahnila Rahim'),"
                                      "(64,'OOP LAB (1-E1) ', ' Core Lab ',' 1-E1 ' , 45, 3, 4, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Madiha Umar'),"
                                      "(65,'OOP LAB (1-E2) ', ' Core Lab ',' 1-E2 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Madiha Umar'),"
                                      "(66,'DLD LAB (1-A1) ', ' Core Lab ',' 1-A1 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Saad Salman'),"
                                      "(67,'DLD LAB (1-A2) ', ' Core Lab ',' 1-A2 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Shams Farooq'),"
                                      "(68,'DLD LAB (1-B1) ', ' Core Lab ',' 1-B1 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Saad Salman'),"
                                      "(69,'DLD LAB (1-B2) ', ' Core Lab ',' 1-B2 ' , 45, 3, 2, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Shoaib Mehboob'),"
                                      "(70,'DLD LAB (1-C1) ', ' Core Lab ',' 1-C1 ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Saba Kanwal'),"
                                      "(71,'DLD LAB (1-C2) ', ' Core Lab ',' 1-C2 ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Saad Salman'),"
                                      "(72,'DLD LAB (1-D1) ', ' Core Lab ',' 1-D1 ' , 45, 3, 5, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Humera Sabir'),"
                                      "(73,'DLD LAB (1-D2) ', ' Core Lab ',' 1-D2 ' , 45, 3, 5, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Fatima Farooq'),"
                                      "(74,'DLD LAB (1-E1) ', ' Core Lab ',' 1-E1 ' , 45, 3, 4, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Humera Sabir'),"
                                      "(75,'DLD LAB (1-E2) ', ' Core Lab ',' 1-E2 ' , 45, 3, 4, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Kainat Iqbal'),"
                                      "(76,'DB LAB (2-A) ', ' Core Lab ',' 2-A ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Turab Ali Kazmi'),"
                                      "(77,'DB LAB (2-B) ', ' Core Lab ',' 2-B ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Usman Kaiser Mughal'),"
                                      "(78,'DB LAB (2-C) ', ' Core Lab ',' 2-C ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Turab Ali Kazmi'),"
                                      "(79,'DB LAB (2-D) ', ' Core Lab ',' 2-D ' , 45, 3, 4, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Usman Kaiser Mughal'),"
                                      "(80,'DB LAB (2-E) ', ' Core Lab ',' 2-E ' , 45, 3, 4, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Ayesha Kamran ul Haq'),"
                                      "(81,'OS LAB (2-A) ', ' Core Lab ',' 2-A ' , 45, 3, 5, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Mehran Khan'),"
                                      "(82,'OS LAB (2-B) ', ' Core Lab ',' 2-B ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Mehran Khan'),"
                                      "(83,'OS LAB (2-C) ', ' Core Lab ',' 2-C ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Shehr Bano'),"
                                      "(84,'OS LAB (2-D) ', ' Core Lab ',' 2-D ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Yasmeen Afzal'),"
                                      "(85,'OS LAB (2-E) ', ' Core Lab ',' 2-E ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Mehran Khan'),"
                                      "(86,'WP LAB (3-A) ', ' Elective Lab ',' 3-A ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Muhammad Usman'),"
                                      "(87,'WP LAB (3-B) ', ' Elective Lab ',' 3-B ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Humera Sabir'),"
                                      "(88,'DM LAB (3-A) ', ' Elective Lab ',' 3-A ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Ali Raza'),"
                                      "(89,'DM LAB (3-B) ', ' Elective Lab ',' 3-B ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Mr Shoaib Mehboob'),"
                                      "(90,'DWH LAB (3-A) ', ' Elective Lab ',' 3-AAA ' , 45, 3, 1, 0, 0, 'N/A', 'N/A', 'N/A', 'Ms Ayesha Kamran ul Haq'),"
                                      "(110,'DE (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Farah Jabeen'),"
                                      "(111,'DE (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Farah Jabeen'),"
                                      "(112,'DE (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Farah Jabeen'),"
                                      "(113,'DE (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Farah Jabeen'),"
                                      "(114,'DE (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Usman Ashraf'),"
                                      "(115,'PST (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Maimona Rasool'),"
                                      "(116,'PST (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Nadia Nauman'),"
                                      "(117,'PST (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Maimona Rasool'),"
                                      "(118,'PST (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Maimona Rasool'),"
                                      "(119,'PST (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Gul-e-Ayesha'),"
                                      "(120,'CPS (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Zunera Malik'),"
                                      "(121,'CPS (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Shahzad Mehmood'),"
                                      "(122,'CPS (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Shahzad Mehmood'),"
                                      "(123,'CPS (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Shahzad Mehmood'),"
                                      "(124,'CPS (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Zunera Malik'),"
                                      "(125,'PF (1-B-R) ', ' Core ',' 1-B-R ' , 45, 4, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Faisal Cheema'),"
                                      "(126,'PF (1-C-R) ', ' Core ',' 1-C-R ' , 45, 1, 4, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Subhan Ullah'),"
                                      "(127,'PF (1-D-R) ', ' Core ',' 1-D-R ' , 45, 1, 4, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Subhan Ullah'),"
                                      "(128,'PF (1-E-R) ', ' Core ',' 1-E-R ' , 45, 1, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Mr Jawwad Hassan'),"
                                      "(129,'PF (1-F-R) ', ' Core ',' 1-F-R ' , 45, 1, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Mr Jawwad Hassan'),"
                                      "(130,'PHY (1-A-R) ', ' Core ',' 1-A-R ' , 45, 1, 6, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Aisha Ijaz'),"
                                      "(131,'PHY (1-B-R) ', ' Core ',' 1-B-R ' , 45, 1, 6, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Aisha Ijaz'),"
                                      "(132,'CAL (1-A-R) ', ' Core ',' 1-A-R ' , 45, 1, 6, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Hamda Khan'),"
                                      "(133,'CAL (1-B-R) ', ' Core ',' 1-B-R ' , 45, 1, 6, 2, 0, 'N/A', 'N/A', 'N/A', 'Ms Hamda Khan'),"
                                      "(134,'DS (2-A-R) ', ' Core ',' 2-A-R ' , 45, 4, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Dr Abdul Waheed Khan'),"
                                      "(135,'DS (2-B-R) ', ' Core ',' 2-B-R ' , 45, 4, 1, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Abdul Waheed Khan'),"
                                      "(136,'DS (2-C-R) ', ' Core ',' 2-C-R ' , 45, 4, 1, 1, 0, 'N/A', 'N/A', 'N/A', 'Mr Shehreyar Rashid'),"
                                      "(137,'COAL (2-A-R) ', ' Core ',' 2-A-R ' , 45, 4, 3, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Sarosh Shahid'),"
                                      "(138,'COAL (2-B-R) ', ' Core ',' 2-B-R ' , 45, 4, 3, 2, 0, 'N/A', 'N/A', 'N/A', 'Mr Ameen Chilwan'),"
                                      "(139,'LA (2-A-R) ', ' Core ',' 2-A-R ' , 45, 4, 2, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Zunera Malik'),"
                                      "(140,'AUTO (2-A-R) ', ' Core ',' 2-A-R ' , 45, 4, 2, 2, 0, 'N/A', 'N/A', 'N/A', 'Dr Arshad Islam'),"
                                      "(141,'CNET (3-A-R) ', ' Core ',' 3-A-R ' , 45, 4, 2, 2, 0, 'N/A', 'N/A', 'N/A', 'Mr Ameen Chilwan'),"
                                      "(142,'HCI (4-A-R) ', ' Core ',' 4-A-R ' , 45, 1.5, 4, 1, 0, 'N/A', 'N/A', 'N/A', 'Ms Saba Rasheed')")
""""('C3-1-4','WP (3-A) ', ' 3-A ' , 45, 2, 2, 1),"
                                      "('C3-2-4','WP (3-B) ', ' 3-B ' , 45, 2, 2, 1),"
                                      "('C3-1-5','DM (3-A) ', ' 3-A ' , 45, 2, 2, 1),"
                                      "('C3-2-5','DM (3-B) ', ' 3-B ' , 45, 2, 2, 1),"
                                      "('C3-1-6','DWH (3-A) ', ' 3-A ' , 45, 2, 4, 1),"""



c.execute("""create table course_instructor (course_number integer references course(CourseID), instructor_number integer references instructor(InstructorID))""")
c.execute("insert into course_instructor Values    (1, 5),"
                                                  "(2, 6),"
                                                  "(3, 5),"
                                                  "(4, 7),"
                                                  "(5, 8),"
                                                  "(6, 10),"
                                                  "(7, 9),"
                                                  "(8, 6),"
                                                  "(9, 4),"
                                                  "(10, 10),"
                                                  "(11, 11),"
                                                  "(12, 2),"
                                                  "(13, 15),"
                                                  "(14, 32),"
                                                  "(15, 11),"
                                                  "(16, 2),"
                                                  "(17, 16),"
                                                  "(18, 32),"
                                                  "(19, 1),"
                                                  "(20, 13),"
                                                  "(21, 3),"
                                                  "(22, 33),"
                                                  "(23, 12),"
                                                  "(24, 13),"
                                                  "(25, 3),"
                                                  "(26, 12),"
                                                  "(27, 14),"
                                                  "(28, 3),"
                                                  "(29, 21), "
                                                  "(30, 17),"
                                                  "(31, 34),"
                                                  "(32, 21),"
                                                  "(33, 17),"
                                                  "(34, 34),"
                                                  "(35, 20),"
                                                  "(36, 19),"
                                                  "(37, 35),"
                                                  "(38, 22),"
                                                  "(39, 18),"
                                                  "(40, 21),"
                                                  "(41, 18),"
                                                  "(42, 23),"
                                                  "(43, 23),"
                                                  "(44, 24),"
                                                  "(45, 25),"
                                                  "(46, 26),"
                                                  "(47, 27),"
                                                  "(48, 22),"
                                                  "(49, 28),"
                                                  "(50, 28),"
                                                  "(51, 31),"
                                                  "(52, 31),"
                                                  "(53, 27),"
                                                  "(54, 13),"
                                                  "(55, 23),"
                                                  "(56, 57),"
                                                  "(57, 58),"
                                                  "(91, 20),"
                                                  "(92, 20),"
                                                  "(93, 19),"
                                                  "(94, 19),"
                                                  "(95, 63),"
                                                  "(96, 28),"
                                                  "(97, 62),"
                                                  "(98, 18),"
                                                  "(99, 61),"
                                                  "(100, 61),"
                                                  "(101, 60),"
                                                  "(102, 60),"
                                                  "(103, 66),"
                                                  "(104, 65),"
                                                  "(105, 57),"
                                                  "(106, 67),"
                                                  "(107, 67),"
                                                  "(108, 68),"
                                                  "(109, 58),"
                                                  "(58, 36),"
                                                  "(59, 37),"
                                                  "(60, 38),"
                                                  "(61, 38),"
                                                  "(62, 39),"
                                                  "(63, 40),"
                                                  "(64, 36),"
                                                  "(65, 36),"
                                                  "(66, 7),"
                                                  "(67, 6),"
                                                  "(68, 7),"
                                                  "(69, 43),"
                                                  "(70, 44),"
                                                  "(71, 7),"
                                                  "(72, 45),"
                                                  "(73, 46),"
                                                  "(74, 45),"
                                                  "(75, 47),"
                                                  "(76, 48),"
                                                  "(77, 49),"
                                                  "(78, 48),"
                                                  "(79, 49),"
                                                  "(80, 50),"
                                                  "(81, 51),"
                                                  "(82, 51),"
                                                  "(83, 52),"
                                                  "(84, 39),"
                                                  "(85, 51),"
                                                  "(86, 55),"
                                                  "(87, 45),"
                                                  "(88, 56),"
                                                  "(89, 43),"
                                                  "(90, 50),"
                                                  "(110, 69),"
                                                  "(111, 69),"
                                                  "(112, 69),"
                                                  "(113, 69),"
                                                  "(114, 70),"
                                                  "(115, 71),"
                                                  "(116, 72),"
                                                  "(117, 71),"
                                                  "(118, 71),"
                                                  "(119, 73),"
                                                  "(120, 74),"
                                                  "(121, 75),"
                                                  "(122, 75),"
                                                  "(123, 75),"
                                                  "(124, 74),"
                                                  "(125, 67),"
                                                  "(126, 65),"
                                                  "(127, 65),"
                                                  "(128, 8),"
                                                  "(129, 8),"
                                                  "(130, 76),"
                                                  "(131, 76),"
                                                  "(132, 77),"
                                                  "(133, 77),"
                                                  "(134, 63),"
                                                  "(135, 63),"
                                                  "(136, 42),"
                                                  "(137, 78),"
                                                  "(138, 79),"
                                                  "(139, 81),"
                                                  "(140, 82),"
                                                  "(141, 79),"
                                                  "(142, 31)")


c.execute("""create table dept (Dept text)""")
c.execute("insert into dept Values ('CS')")


c.execute("""create table dept_course (name text references dept(Dept), course_number integer references course(CourseID))""")
c.execute("insert into dept_course Values ('CS', 1),"
                                         "('CS', 2),"
                                         "('CS', 3),"
                                         "('CS', 4),"
                                         "('CS', 5),"
                                         "('CS', 6),"
                                         "('CS', 7),"
                                         "('CS', 8),"
                                         "('CS', 9),"
                                         "('CS', 10),"
                                          "('CS', 11),"
                                          "('CS', 12),"
                                          "('CS', 13),"
                                          "('CS', 14),"
                                          "('CS', 15),"
                                          "('CS', 16),"
                                          "('CS', 17),"
                                          "('CS', 18),"
                                          "('CS', 19),"
                                          "('CS', 20),"
                                          "('CS', 21),"
                                          "('CS', 22),"
                                          "('CS', 23),"
                                          "('CS', 24),"
                                          "('CS', 25),"
                                          "('CS', 26),"
                                          "('CS', 27),"
                                          "('CS', 28),"
                                          "('CS', 29),"
                                          "('CS', 30),"
                                          "('CS', 31),"
                                          "('CS', 32),"
                                          "('CS', 33),"
                                          "('CS', 34),"
                                          "('CS', 35),"
                                          "('CS', 36),"
                                          "('CS', 37),"
                                          "('CS', 38),"
                                          "('CS', 39),"
                                          "('CS', 40),"
                                          "('CS', 41),"
                                          "('CS', 42),"
                                          "('CS', 43),"
                                          "('CS', 44),"
                                          "('CS', 45),"
                                          "('CS', 46),"
                                          "('CS', 47),"
                                          "('CS', 48),"
                                          "('CS', 49),"
                                          "('CS', 50),"
                                          "('CS', 51),"
                                          "('CS', 52),"
                                          "('CS', 53),"
                                          "('CS', 54),"
                                          "('CS', 55),"
                                          "('CS', 56),"
                                          "('CS', 57),"
                                          "('CS', 91),"
                                          "('CS', 92),"
                                          "('CS', 93),"
                                          "('CS', 94),"
                                          "('CS', 95),"
                                          "('CS', 96),"
                                          "('CS', 97),"
                                          "('CS', 98),"
                                          "('CS', 99),"
                                          "('CS', 100),"
                                          "('CS', 101),"
                                          "('CS', 102),"
                                          "('CS', 103),"
                                          "('CS', 104),"
                                          "('CS', 105),"
                                          "('CS', 106),"
                                          "('CS', 107),"
                                          "('CS', 108),"
                                          "('CS', 109),"
                                          "('CS', 58),"
                                          "('CS', 59),"
                                          "('CS', 60),"
                                          "('CS', 61),"
                                          "('CS', 62),"
                                          "('CS', 63),"
                                          "('CS', 64),"
                                          "('CS', 65),"
                                          "('CS', 66),"
                                          "('CS', 67),"
                                          "('CS', 68),"
                                          "('CS', 69),"
                                          "('CS', 70),"
                                          "('CS', 71),"
                                          "('CS', 72),"
                                          "('CS', 73),"
                                          "('CS', 74),"
                                          "('CS', 75),"
                                          "('CS', 76),"
                                          "('CS', 77),"
                                          "('CS', 78),"
                                          "('CS', 79),"
                                          "('CS', 80),"
                                          "('CS', 81),"
                                          "('CS', 82),"
                                          "('CS', 83),"
                                          "('CS', 84),"
                                          "('CS', 85),"
                                          "('CS', 86),"
                                          "('CS', 87),"
                                          "('CS', 88),"
                                          "('CS', 89),"
                                          "('CS', 90),"
                                          "('CS', 110),"
                                          "('CS', 111),"
                                          "('CS', 112),"
                                          "('CS', 113),"
                                          "('CS', 114),"
                                          "('CS', 115),"
                                          "('CS', 116),"
                                          "('CS', 117),"
                                          "('CS', 118),"
                                          "('CS', 119),"
                                          "('CS', 120),"
                                          "('CS', 121),"
                                          "('CS', 122),"
                                          "('CS', 123),"
                                          "('CS', 124),"
                                          "('CS', 125),"
                                          "('CS', 126),"
                                          "('CS', 127),"
                                          "('CS', 128),"
                                          "('CS', 129),"
                                          "('CS', 130),"
                                          "('CS', 131),"
                                          "('CS', 132),"
                                          "('CS', 133),"
                                          "('CS', 134),"
                                          "('CS', 135),"
                                          "('CS', 136),"
                                          "('CS', 137),"
                                          "('CS', 138),"
                                          "('CS', 139),"
                                          "('CS', 140),"
                                          "('CS', 141),"
                                          "('CS', 142)")



c.execute("""create table course_timing (CourseNumber integer, CourseName text, Timing text, Teacher text, Room text, Status text) """)
c.execute("insert into course_timing Values     (1,'OOP (1-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(2,'DLD (1-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(3,'OOP (1-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(4,'DLD (1-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(5,'OOP (1-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(6,'DLD (1-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(7,'OOP (1-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(8,'DLD (1-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(9,'OOP (1-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(10,'DLD (1-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(11,'DB (2-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(12,'OS (2-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(13,'ALGO (2-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(14,'MM (2-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(15,'DB (2-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(16,'OS (2-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(17,'ALGO (2-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(18,'MM (2-B) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(19,'DB (2-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(20,'OS (2-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(21,'ALGO (2-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(22,'MM (2-C) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(23,'DB (2-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(24,'OS (2-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(25,'ALGO (2-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(26,'DB (2-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(27,'OS (2-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(28,'ALGO (2-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(29,'ALGO-3 (3-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(30,'SE (3-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(31,'OB (3-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(32,'ALGO-3 (3-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(33,'SE (3-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(34,'OB (3-B) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(35,'ALGO-3 (3-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(36,'SE (3-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(37,'OB (3-C) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(38,'ALGO-3 (3-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(39,'SE (3-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(40,'ALGO-3 (3-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(41,'SE (3-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(42,'PIT (4-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(43,'PIT (4-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(44,'PIT (4-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(45,'PIT (4-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(46,'PIT (4-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(47,'PDC (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(48,'PDC (4-B) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(49,'NSEC (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(50,'NSEC (4-B) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(51,'UX (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(52,'UX (4-B) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(53,'IBC (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(54,'IOT (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(55,'ST (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(56,'AMAD (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(57,'DM (4-A) ', ' Elective ', ' A ', ' A ', ' A '),"
                                              "(91,'ADV. ALGO (5-Y1) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(92,'ADV. ALGO (5-Y2) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(93,'TPL (5-Y1) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(94,'TPL (5-Y2) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(95,'ADV. CNET (5-Z) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(96,'CYB. SEC (5-Z) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(97,'ADV. QA SEC (5-X) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(98,'ADV. S/W REQ ENG (5-X) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(99,'BIG DATA (5-U1) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(100,'BIG DATA (5-U2) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(101,'ML DS (5-U1) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(102,'ML DS (5-U2) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(103,'MBT (5-X) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(104,'IOT SEC (5-Z) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(105,'UXE (5-Y) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(106,'D. VIS (5-U1) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(107,'D. VIS (5-U2) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(108,'BIO-INFO (5-U) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(109,'AIP (5-U) ', ' Core ', ' A ', ' A ', ' A '),"
                                              "(58,'OOP LAB (1-A) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(59,'OOP LAB (1-B) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(60,'OOP LAB (1-C1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(61,'OOP LAB (1-C2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(62,'OOP LAB (1-D1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(63,'OOP LAB (1-D2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(64,'OOP LAB (1-E1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(65,'OOP LAB (1-E2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(66,'DLD LAB (1-A1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(67,'DLD LAB (1-A2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(68,'DLD LAB (1-B1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(69,'DLD LAB (1-B2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(70,'DLD LAB (1-C1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(71,'DLD LAB (1-C2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(72,'DLD LAB (1-D1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(73,'DLD LAB (1-D2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(74,'DLD LAB (1-E1) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(75,'DLD LAB (1-E2) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(76,'DB LAB (2-A) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(77,'DB LAB (2-B) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(78,'DB LAB (2-C) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(79,'DB LAB (2-D) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(80,'DB LAB (2-E) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(81,'OS LAB (2-A) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(82,'OS LAB (2-B) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(83,'OS LAB (2-C) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(84,'OS LAB (2-D) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(85,'OS LAB (2-E) ', ' Core Lab ', ' A ', ' A ', ' A '),"
                                              "(86,'WP LAB (3-A) ', ' Elective Lab ', ' A ', ' A ', ' A '),"
                                              "(87,'WP LAB (3-B) ', ' Elective Lab ', ' A ', ' A ', ' A '),"
                                              "(88,'DM LAB (3-A) ', ' Elective Lab ', ' A ', ' A ', ' A '),"
                                              "(89,'DM LAB (3-B) ', ' Elective Lab ', ' A ', ' A ', ' A '),"
                                              "(90,'DWH LAB (3-A) ', ' Elective Lab ', ' A ', ' A ', ' A '),"
                                                            "(110,'DE (1-A) ', ' Core ', ' A ', ' A ', ' A '), "
                                                            "(111,'DE (1-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(112,'DE (1-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(113,'DE (1-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(114,'DE (1-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(115,'PST (1-A) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(116,'PST (1-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(117,'PST (1-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(118,'PST (1-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(119,'PST (1-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(120,'CPS (1-A) ', ' Core ', ' A ', ' A ', ' A '), "
                                                            "(121,'CPS (1-B) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(122,'CPS (1-C) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(123,'CPS (1-D) ', ' Core ', ' A ', ' A ', ' A '),"
                                                            "(124,'CPS (1-E) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(125,'PF (1-B-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(126,'PF (1-C-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(127,'PF (1-D-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(128,'PF (1-E-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(129,'PF (1-F-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(130,'PHY (1-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(131,'PHY (1-B-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(132,'CAL (1-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(133,'CAL (1-B-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(134,'DS (2-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(135,'DS (2-B-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(136,'DS (2-C-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(137,'COAL (2-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(138,'COAL (2-B-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(139,'LA (2-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(140,'AUTO (2-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(141,'CNET (3-A-R) ', ' Core ', ' A ', ' A ', ' A '),"
                                                              "(142,'HCI (4-A-R) ', ' Core ', ' A ', ' A ', ' A ')")


conn.commit()

conn.close()



