import sqlite3 as sql
conn  = sql.connect('class_schedule_4.db')
c = conn.cursor()

c.execute("""create table schedule (S text)""")
c.execute("insert into schedule values ('MT1')")

c.execute("""create table room (RNumber text PRIMARY KEY, RoomType text, Capacity integer)""")
c.execute("insert into room Values ('C301', 'Classroom', 50),"
                                  "('C302', 'Classroom', 50),"
                                  "('C303', 'Classroom', 50),"
                                  "('C304', 'Classroom', 50),"
                                  "('C305', 'Classroom', 50),"
                                  "('C306', 'Classroom', 50),"
                                  "('C307', 'Classroom', 50),"
                                  "('C308', 'Classroom', 50),"
                                  "('C309', 'Classroom', 50),"
                                  "('C310', 'Classroom', 50),"
                                  "('C311', 'Classroom', 50),"
                                  "('C312', 'Classroom', 50),"
                                  "('Margala 1', 'Lab', 50),"
                                  "('Karakoram', 'Lab', 50),"
                                  "('Margala 3', 'Lab', 50),"
                                  "('Margala 4', 'Lab', 50),"
                                  "('Rohtas ', 'Lab', 50),"
                                  "('Rawal 1', 'Lab', 50),"
                                  "('Khyber 3', 'Lab', 50),"
                                  "('DLD 1', 'Lab', 50),"
                                  "('DLD 2', 'Lab', 50)")


c.execute("""create table meeting_time (MeetingTimeID text PRIMARY KEY, Time text, Checker int, Matcher int)""")
c.execute("insert into meeting_time Values ('MT1', 'Mon, Wed, Fri 09:00 - 10:00', 0, 1),"
                                          "('MT2', 'Mon, Wed, Fri 10:00 - 11:00', 0, 2),"
                                          "('MT3', 'Mon, Wed, Fri 11:00 - 12:00', 0, 3),"
                                          "('MT4', 'Mon, Wed, Fri 12:00 - 01:00', 0, 4),"
                                          "('MT5', 'Mon, Wed, Fri 01:00 - 02:00', 0, 5),"
                                          "('MT6', 'Mon, Wed, Fri 02:00 - 03:00', 0, 6),"
                                          "('MT7', 'Mon, Wed, Fri 03:00 - 04:00', 0, 7),"
                                          "('MT8', 'Mon, Wed, Fri 04:00 - 05:00', 0, 8),"
                                          "('MT9', 'Mon, Wed, Fri 05:00 - 06:00', 0, 9),"
                                          "('MT10', 'Tue, Wed, Thurs 09:00 - 10:00', 0, 10),"
                                          "('MT11', 'Tue, Wed, Thurs 10:00 - 11:00', 0, 11),"
                                          "('MT12', 'Tue, Wed, Thurs 11:00 - 12:00', 0, 12),"
                                          "('MT13', 'Tue, Wed, Thurs 12:00 - 01:00', 0, 13),"
                                          "('MT14', 'Tue, Wed, Thurs 01:00 - 02:00', 0, 14),"
                                          "('MT15', 'Tue, Wed, Thurs 02:00 - 03:00', 0, 15),"
                                          "('MT16', 'Tue, Wed, Thurs 03:00 - 04:00', 0, 16),"
                                          "('MT17', 'Tue, Wed, Thurs 04:00 - 05:00', 0, 17),"
                                          "('MT18', 'Tue, Wed, Thurs 05:00 - 06:00', 0, 18),"
                                          "('MT19', 'Wed, Thurs, Fri 09:00 - 10:00', 0, 19),"
                                          "('MT20', 'Wed, Thurs, Fri 10:00 - 11:00', 0, 20),"
                                          "('MT21', 'Wed, Thurs, Fri 11:00 - 12:00', 0, 21),"
                                          "('MT22', 'Wed, Thurs, Fri 12:00 - 01:00', 0, 22),"
                                          "('MT23', 'Wed, Thurs, Fri 01:00 - 02:00', 0, 23),"
                                          "('MT24', 'Wed, Thurs, Fri 02:00 - 03:00', 0, 24),"
                                          "('MT25', 'Wed, Thurs, Fri 03:00 - 04:00', 0, 25),"
                                          "('MT26', 'Wed, Thurs, Fri 04:00 - 05:00', 0, 26),"
                                          "('MT27', 'Wed, Thurs, Fri 05:00 - 06:00', 0, 27),"
                                          "('MT28', 'Mon, Tue 09:00 - 10:30', 0, 28),"
                                          "('MT29', 'Mon, Tue 10:30 - 12:00', 0, 29),"
                                          "('MT30', 'Mon, Tue 12:00 - 01:30', 0, 30),"
                                          "('MT31', 'Mon, Tue 01:30 - 03:00', 0, 31),"
                                          "('MT32', 'Mon, Tue 03:00 - 04:30', 0, 32),"
                                          "('MT33', 'Mon, Tue 04:30 - 06:00', 0, 33),"
                                          "('MT34', 'Tue, Wed 09:00 - 10:30', 0, 34),"
                                          "('MT35', 'Tue, Wed 10:30 - 12:00', 0, 35),"
                                          "('MT36', 'Tue, Wed 12:00 - 01:30', 0, 36),"
                                          "('MT37', 'Tue, Wed 01:30 - 03:00', 0, 37),"
                                          "('MT38', 'Tue, Wed 03:00 - 04:30', 0, 38),"
                                          "('MT39', 'Tue, Wed 04:30 - 06:00', 0, 39),"
                                          "('MT40', 'Tue, Thurs 09:00 - 10:30', 0, 40),"
                                          "('MT41', 'Tue, Thurs 10:30 - 12:00', 0, 41),"
                                          "('MT42', 'Tue, Thurs 12:00 - 01:30', 0, 42),"
                                          "('MT43', 'Tue, Thurs 01:30 - 03:00', 0, 43),"
                                          "('MT44', 'Tue, Thurs 03:00 - 04:30', 0, 44),"
                                          "('MT45', 'Tue, Thurs 04:30 - 06:00', 0, 45),"
                                          "('MT46', 'Mon, Fri 09:00 - 10:30', 0, 46),"
                                          "('MT47', 'Mon, Fri 10:30 - 12:00', 0, 47),"
                                          "('MT48', 'Mon, Fri 12:00 - 01:30', 0, 48),"
                                          "('MT49', 'Mon, Fri 01:30 - 03:00', 0, 49),"
                                          "('MT50', 'Mon, Fri 03:00 - 04:30', 0, 50),"
                                          "('MT51', 'Mon, Fri 04:30 - 06:00', 0, 51),"
                                          "('MT52', 'Tue, Thurs, Fri 09:00 - 10:00', 0, 52),"
                                          "('MT53', 'Tue, Thurs, Fri 10:00 - 11:00', 0, 53),"
                                          "('MT54', 'Tue, Thurs, Fri 11:00 - 12:00', 0, 54),"
                                          "('MT55', 'Tue, Thurs, Fri 12:00 - 01:00', 0, 55),"
                                          "('MT56', 'Tue, Thurs, Fri 01:00 - 02:00', 0, 56),"
                                          "('MT57', 'Tue, Thurs, Fri 02:00 - 03:00', 0, 57),"
                                          "('MT58', 'Tue, Thurs, Fri 03:00 - 04:00', 0, 58),"
                                          "('MT59', 'Tue, Thurs, Fri 04:00 - 05:00', 0, 59),"
                                          "('MT60', 'Tue, Thurs, Fri 05:00 - 06:00', 0, 60),"
                                          "('MT61', 'Mon 09:00 - 11:00', 0, 61),"
                                          "('MT62', 'Mon 11:00 - 01:00', 0, 62),"
                                          "('MT63', 'Mon 01:00 - 03:00', 0, 63),"
                                          "('MT64', 'Mon 03:00 - 05:00', 0, 64),"
                                          "('MT65', 'Tue 09:00 - 11:00', 0, 65),"
                                          "('MT66', 'Tue 11:00 - 01:00', 0, 66),"
                                          "('MT67', 'Tue 01:00 - 03:00', 0, 67),"
                                          "('MT68', 'Tue 03:00 - 05:00', 0, 68),"
                                          "('MT69', 'Wed 09:00 - 11:00', 0, 69),"
                                          "('MT70', 'Wed 11:00 - 01:00', 0, 70),"
                                          "('MT71', 'Wed 01:00 - 03:00', 0, 71),"
                                          "('MT72', 'Wed 03:00 - 05:00', 0, 72),"
                                          "('MT73', 'Thu 09:00 - 11:00', 0, 73),"
                                          "('MT74', 'Thu 11:00 - 01:00', 0, 74),"
                                          "('MT75', 'Thu 01:00 - 03:00', 0, 75),"
                                          "('MT76', 'Thu 03:00 - 05:00', 0, 76),"
                                          "('MT77', 'Fri 09:00 - 11:00', 0, 77),"
                                          "('MT78', 'Fri 11:00 - 01:00', 0, 78),"
                                          "('MT79', 'Fri 01:00 - 03:00', 0, 79),"
                                          "('MT80', 'Fri 03:00 - 05:00', 0, 80),"
                                          "('MT81', 'Mon 09:00 - 12:00', 0, 81),"
                                          "('MT82', 'Mon 12:00 - 03:00', 0, 82),"
                                          "('MT83', 'Mon 03:00 - 06:00', 0, 83),"
                                          "('MT84', 'Tue 09:00 - 12:00', 0, 84),"
                                          "('MT85', 'Tue 12:00 - 03:00', 0, 85),"
                                          "('MT86', 'Tue 03:00 - 06:00', 0, 86),"
                                          "('MT87', 'Wed 09:00 - 12:00', 0, 87),"
                                          "('MT88', 'Wed 12:00 - 03:00', 0, 88),"
                                          "('MT89', 'Wed 03:00 - 06:00', 0, 89),"
                                          "('MT90', 'Thu 09:00 - 12:00', 0, 90),"
                                          "('MT91', 'Thu 12:00 - 03:00', 0, 91),"
                                          "('MT92', 'Thu 03:00 - 06:00', 0, 92),"
                                          "('MT93', 'Fri 09:00 - 12:00', 0, 93),"
                                          "('MT94', 'Fri 12:00 - 03:00', 0, 94),"
                                          "('MT95', 'Fri 03:00 - 06:00', 0, 95),"
                                          "('MT96', 'Mon, Thurs, Fri 09:00 - 10:00', 0, 96),"
                                          "('MT97', 'Mon, Thurs, Fri 10:00 - 11:00', 0, 97),"
                                          "('MT98', 'Mon, Thurs, Fri 11:00 - 12:00', 0, 98),"
                                          "('MT99', 'Mon, Thurs, Fri 12:00 - 01:00', 0, 99),"
                                          "('MT100', 'Mon, Thurs, Fri 01:00 - 02:00', 0, 100),"
                                          "('MT101', 'Mon, Thurs, Fri 02:00 - 03:00', 0, 101),"
                                          "('MT102', 'Mon, Thurs, Fri 03:00 - 04:00', 0, 102),"
                                          "('MT103', 'Mon, Thurs, Fri 04:00 - 05:00', 0, 103),"
                                          "('MT104', 'Mon, Thurs, Fri 05:00 - 06:00', 0, 104),"
                                          "('MT105', 'Wed, Thurs 09:00 - 10:30', 0, 105),"
                                          "('MT106', 'Wed, Thurs 10:30 - 12:00', 0, 106),"
                                          "('MT107', 'Wed, Thurs 12:00 - 01:30', 0, 107),"
                                          "('MT108', 'Wed, Thurs 01:30 - 03:00', 0, 108),"
                                          "('MT109', 'Wed, Thurs 03:00 - 04:30', 0, 109),"
                                          "('MT110', 'Wed, Thurs 04:30 - 06:00', 0, 110)")


c.execute("""create table instructor (InstructorID integer PRIMARY KEY, Name text, Spacer int, Spacercheck int)""")
c.execute("insert into instructor Values     (1, ' Dr Asif Naeem ', 0, 0),"
                                            "(2, ' Dr Hasan Mujtaba ', 0, 0),"
                                            "(3, ' Ms Noor ul Ain ', 0, 0),"
                                            "(4, ' Mr Hassan Raza ', 0, 0),"
                                            "(5, ' Dr Naveed Ahmad ', 0, 0),"
                                            "(6, ' Mr Shams Farooq ', 1, 0),"
                                            "(7, ' Mr Saad Salman ', 0, 0),"
                                            "(8, ' Mr Jawwad Hassan ', 0, 0),"
                                            "(9, ' Mr Hassan Mustafa ', 0, 0),"
                                            "(10, ' Ms Mehreen Alam ', 0, 0),"
                                            "(11, ' Dr Ejaz Ahmed ', 0, 0),"
                                            "(12, ' Dr Asma Ahmad ', 0, 0),"
                                            "(13, ' Dr Adnan Tariq ', 1, 0),"
                                            "(14, ' Ms Sidra Khalid ', 0, 0),"
                                            "(15, ' Dr Hammad Naveed  ', 0, 0),"
                                            "(16, ' Mr Umair Arshad ', 0, 0),"
                                            "(17, ' Mr Bilal Khalid Dar  ', 1, 0),"
                                            "(18, ' Dr Irum Inayat ', 0, 0),"
                                            "(19, ' Dr Labiba Fahad  ', 0, 0),"
                                            "(20, ' Dr Hammad Majeed  ', 1, 0),"
                                            "(21, ' Mr Ahmed Nawaz  ', 0, 0),"
                                            "(22, ' Dr Shujaat Hussain  ', 0, 0),"
                                            "(23, ' Ms Uzma Bibi  ', 0, 0),"
                                            "(24, ' Dr Atif Mughees  ', 0, 0),"
                                            "(25, ' Mr Barkan Saeed  ', 0, 0),"
                                            "(26, ' Mr Sabqat Mansoor  ', 0, 0),"
                                            "(27, ' Dr Ehtishaam Zahoor  ', 0, 0),"
                                            "(28, ' Dr Muhammad Asim  ', 1, 0),"
                                            "(29, ' Dr  Affan A. Syed  ', 0, 0),"
                                            "(30, ' Dr Omer Beg  ', 0, 0),"
                                            "(31, ' Ms Saba Rasheed  ', 0, 0),"
                                            "(32, ' Dr Aqeel Shahzad  ', 0, 0),"
                                            "(33, ' Ms Sahar Arshad  ', 0, 0),"
                                            "(34, ' Ms Azka Sameen  ', 0, 0),"
                                            "(35, ' Ms Inji Akhtar  ', 0, 0),"
                                              "(36, ' Ms Madiha Umar  ', 0, 0),"
                                              "(37, ' Mr Majid Hussain  ', 0, 0),"
                                              "(38, ' Ms Huma Altaf', 0, 0),"
                                              "(39, ' Ms Yasmeen Afzal  ', 0, 0),"
                                              "(40, ' Ms Shahnila Rahim  ', 0, 0),"
                                              "(41, ' Ms Shafaq Riaz Bhatti  ', 0, 0),"
                                              "(42, ' Mr Shehreyar Rashid ', 0, 0),"
                                              "(43, ' Mr Shoaib Mehboob  ', 0, 0),"
                                              "(44, ' Ms Saba Kanwal  ', 0, 0),"
                                              "(45, ' Ms Humera Sabir', 0, 0),"
                                              "(46, ' Ms Fatima Farooq  ', 0, 0),"
                                              "(47, ' Ms Kainat Iqbal  ', 0, 0),"
                                              "(48, ' Mr Turab Ali Kazmi ', 0, 0),"
                                              "(49, ' Mr Usman Kaiser Mughal ', 0, 0),"
                                              "(50, ' Ms Ayesha Kamran ul Haq ', 0, 0),"
                                              "(51, ' Ms Mehran Khan ', 0, 0),"
                                              "(52, ' Ms Shehr Bano ', 0, 0),"
                                              "(53, ' Mr Zia ur Rehman ', 0, 0),"
                                              "(54, ' Ms Anmol Bilal ', 0, 0),"
                                              "(55, ' Mr Muhammad Usman  ', 0, 0),"
                                              "(56, ' Mr Ali Raza', 0, 0),"
                                              "(57, ' Dr Amna Basharat  ', 0, 0),"
                                              "(58, ' Dr Omer Ishaq  ', 0, 0),"
                                              "(59, ' Dr Atif Jilani  ', 0, 0)")

c.execute("""create table course (CourseID integer PRIMARY KEY, CourseName text, CourseType text, Section text, MaxNumOfStudents int, Tpreference int, Dpreference integer, qpreference integer)""")

c.execute("insert into course Values   (1,'OOP (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1),"
                                      "(2,'DLD (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1),"
                                      "(3,'OOP (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1),"
                                      "(4,'DLD (1-B) ', ' Core ',' 1-B ' , 45, 1, 1, 1),"
                                      "(5,'OOP (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1),"
                                      "(6,'DLD (1-C) ', ' Core ',' 1-C ' , 45, 1, 1, 1),"
                                      "(7,'OOP (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1),"
                                      "(8,'DLD (1-D) ', ' Core ',' 1-D ' , 45, 1, 1, 1),"
                                      "(9,'OOP (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1),"
                                      "(10,'DLD (1-E) ', ' Core ',' 1-E ' , 45, 1, 1, 1),"
                                      "(11,'DB (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1),"
                                      "(12,'OS (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1),"
                                      "(13,'ALGO (2-A) ', ' Core ',' 2-A ' , 45, 1, 2, 1),"
                                      "(14,'MM (2-A) ', ' Elective ',' 2-A ' , 45, 1.5, 2, 2),"
                                      "(15,'DB (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1),"
                                      "(16,'OS (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1),"
                                      "(17,'ALGO (2-B) ', ' Core ',' 2-B ' , 45, 1, 2, 1),"
                                      "(18,'MM (2-B) ', ' Elective ',' 2-B ' , 45, 1.5, 2, 2),"
                                      "(19,'DB (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1),"
                                      "(20,'OS (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1),"
                                      "(21,'ALGO (2-C) ', ' Core ',' 2-C ' , 45, 1, 2, 1),"
                                      "(22,'MM (2-C) ', ' Elective ',' 2-C ' , 45, 1.5, 2, 2),"
                                      "(23,'DB (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1),"
                                      "(24,'OS (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1),"
                                      "(25,'ALGO (2-D) ', ' Core ',' 2-D ' , 45, 1, 2, 1),"
                                      "(26,'DB (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1),"
                                      "(27,'OS (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1),"
                                      "(28,'ALGO (2-E) ', ' Core ',' 2-E ' , 45, 1, 2, 1),"
                                      "(29,'ALGO-3 (3-A) ', ' Core ',' 3-A ' , 45, 1, 4, 1),"
                                      "(30,'SE (3-A) ', ' Core ',' 3-A ' , 45, 1, 4, 1),"
                                      "(31,'OB (3-A) ', ' Elective ',' 3-A ' , 45, 1.5, 3, 2),"
                                      "(32,'ALGO-3 (3-B) ', ' Core ',' 3-B ' , 45, 1, 4, 1),"
                                      "(33,'SE (3-B) ', ' Core ',' 3-B ' , 45, 1, 4, 1),"
                                      "(34,'OB (3-B) ', ' Elective ',' 3-B ' , 45, 1.5, 3, 2),"
                                      "(35,'ALGO-3 (3-C) ', ' Core ',' 3-C ' , 45, 1, 4, 1),"
                                      "(36,'SE (3-C) ', ' Core ',' 3-C ' , 45, 1, 4, 1),"
                                      "(37,'OB (3-C) ', ' Elective ',' 3-C ' , 45, 1.5, 3, 2),"
                                      "(38,'ALGO-3 (3-D) ', ' Core ',' 3-D ' , 45, 1, 4, 1),"
                                      "(39,'SE (3-D) ', ' Core ',' 3-D ' , 45, 1, 4, 1),"
                                      "(40,'ALGO-3 (3-E) ', ' Core ',' 3-E ' , 45, 1, 4, 1),"
                                      "(41,'SE (3-E) ', ' Core ',' 3-E ' , 45, 1, 4, 1),"
                                      "(42,'PIT (4-A) ', ' Core ',' 4-A ' , 45, 1.5, 4, 1),"
                                      "(43,'PIT (4-B) ', ' Core ',' 4-B ' , 45, 1.5, 4, 1),"
                                      "(44,'PIT (4-C) ', ' Core ',' 4-C ' , 45, 1.5, 4, 1),"
                                      "(45,'PIT (4-D) ', ' Core ',' 4-D ' , 45, 1.5, 4, 1),"
                                      "(46,'PIT (4-E) ', ' Core ',' 4-E ' , 45, 1.5, 4, 1),"
                                      "(47,'PDC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 1),"
                                      "(48,'PDC (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 3, 1),"
                                      "(49,'NSEC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 1, 1),"
                                      "(50,'NSEC (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 5, 1),"
                                      "(51,'UX (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 2),"
                                      "(52,'UX (4-B) ', ' Elective ',' 4-B ' , 45, 1.5, 3, 2),"
                                      "(53,'IBC (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 1),"
                                      "(54,'IOT (4-A) ', ' Elective ',' 4-A ' , 45, 1.5, 3, 2),"
                                      "(55,'ST (4-A) ', ' Elective ',' 4-A' , 45, 2, 1, 2),"
                                      "(56,'AMAD (4-A) ', ' Elective ',' 4-A' , 45, 2, 1, 2),"
                                      "(57,'DM (4-A) ', ' Elective ',' 4-AA' , 45, 2, 1, 2),"
                                      "(58,'OOP LAB (1-A) ', ' Core Lab ',' 1-A ' , 45, 3, 2, 0),"
                                      "(59,'OOP LAB (1-B) ', ' Core Lab ',' 1-B ' , 45, 3, 2, 0),"
                                      "(60,'OOP LAB (1-C1) ', ' Core Lab ',' 1-C1 ' , 45, 3, 2, 0),"
                                      "(61,'OOP LAB (1-C2) ', ' Core Lab ',' 1-C2 ' , 45, 3, 2, 0),"
                                      "(62,'OOP LAB (1-D1) ', ' Core Lab ',' 1-D1 ' , 45, 3, 2, 0),"
                                      "(63,'OOP LAB (1-D2) ', ' Core Lab ',' 1-D2 ' , 45, 3, 2, 0),"
                                      "(64,'OOP LAB (1-E1) ', ' Core Lab ',' 1-E1 ' , 45, 3, 4, 0),"
                                      "(65,'OOP LAB (1-E2) ', ' Core Lab ',' 1-E2 ' , 45, 3, 2, 0),"
                                      "(66,'DLD LAB (1-A1) ', ' Core Lab ',' 1-A1 ' , 45, 3, 2, 0),"
                                      "(67,'DLD LAB (1-A2) ', ' Core Lab ',' 1-A2 ' , 45, 3, 2, 0),"
                                      "(68,'DLD LAB (1-B1) ', ' Core Lab ',' 1-B1 ' , 45, 3, 2, 0),"
                                      "(69,'DLD LAB (1-B2) ', ' Core Lab ',' 1-B2 ' , 45, 3, 2, 0),"
                                      "(70,'DLD LAB (1-C1) ', ' Core Lab ',' 1-C1 ' , 45, 3, 1, 0),"
                                      "(71,'DLD LAB (1-C2) ', ' Core Lab ',' 1-C2 ' , 45, 3, 1, 0),"
                                      "(72,'DLD LAB (1-D1) ', ' Core Lab ',' 1-D1 ' , 45, 3, 5, 0),"
                                      "(73,'DLD LAB (1-D2) ', ' Core Lab ',' 1-D2 ' , 45, 3, 5, 0),"
                                      "(74,'DLD LAB (1-E1) ', ' Core Lab ',' 1-E1 ' , 45, 3, 4, 0),"
                                      "(75,'DLD LAB (1-E2) ', ' Core Lab ',' 1-E2 ' , 45, 3, 4, 0),"
                                      "(76,'DB LAB (2-A) ', ' Core Lab ',' 2-A ' , 45, 3, 1, 0),"
                                      "(77,'DB LAB (2-B) ', ' Core Lab ',' 2-B ' , 45, 3, 1, 0),"
                                      "(78,'DB LAB (2-C) ', ' Core Lab ',' 2-C ' , 45, 3, 1, 0),"
                                      "(79,'DB LAB (2-D) ', ' Core Lab ',' 2-D ' , 45, 3, 4, 0),"
                                      "(80,'DB LAB (2-E) ', ' Core Lab ',' 2-E ' , 45, 3, 4, 0),"
                                      "(81,'OS LAB (2-A) ', ' Core Lab ',' 2-A ' , 45, 3, 5, 0),"
                                      "(82,'OS LAB (2-B) ', ' Core Lab ',' 2-B ' , 45, 3, 1, 0),"
                                      "(83,'OS LAB (2-C) ', ' Core Lab ',' 2-C ' , 45, 3, 1, 0),"
                                      "(84,'OS LAB (2-D) ', ' Core Lab ',' 2-D ' , 45, 3, 1, 0),"
                                      "(85,'OS LAB (2-E) ', ' Core Lab ',' 2-E ' , 45, 3, 1, 0),"
                                      "(86,'WP LAB (3-A) ', ' Elective Lab ',' 3-A ' , 45, 3, 1, 0),"
                                      "(87,'WP LAB (3-B) ', ' Elective Lab ',' 3-B ' , 45, 3, 1, 0),"
                                      "(88,'DM LAB (3-A) ', ' Elective Lab ',' 3-A ' , 45, 3, 1, 0),"
                                      "(89,'DM LAB (3-B) ', ' Elective Lab ',' 3-B ' , 45, 3, 1, 0),"
                                      "(90,'DWH LAB (3-A) ', ' Elective Lab ',' 3-AAA ' , 45, 3, 1, 0)")
""""('C3-1-4','WP (3-A) ', ' 3-A ' , 45, 2, 2, 1),"
                                      "('C3-2-4','WP (3-B) ', ' 3-B ' , 45, 2, 2, 1),"
                                      "('C3-1-5','DM (3-A) ', ' 3-A ' , 45, 2, 2, 1),"
                                      "('C3-2-5','DM (3-B) ', ' 3-B ' , 45, 2, 2, 1),"
                                      "('C3-1-6','DWH (3-A) ', ' 3-A ' , 45, 2, 4, 1),"""

"""c.execute("insert into course(CourseName, CourseType , Section, MaxNumOfStudents , Tpreference , Dpreference , qpreference ) Values   ('OOP (1-A) ', ' Core ',' 1-A ' , 45, 1, 1, 1)")
c.execute("""""")"""""

c.execute("""create table course_instructor (course_number integer references course(CourseID), instructor_number integer references instructor(InstructorID))""")
c.execute("insert into course_instructor Values    (1, 5),"
                                                  "(2, 6),"
                                                  "(3, 5),"
                                                  "(4, 7),"
                                                  "(5, 8),"
                                                  "(6, 10),"
                                                  "(7, 9),"
                                                  "(8, 6),"
                                                  "(9, 4),"
                                                  "(10, 10),"
                                                  "(11, 11),"
                                                  "(12, 2),"
                                                  "(13, 15),"
                                                  "(14, 32),"
                                                  "(15, 11),"
                                                  "(16, 2),"
                                                  "(17, 16),"
                                                  "(18, 32),"
                                                  "(19, 1),"
                                                  "(20, 13),"
                                                  "(21, 3),"
                                                  "(22, 33),"
                                                  "(23, 12),"
                                                  "(24, 13),"
                                                  "(25, 3),"
                                                  "(26, 12),"
                                                  "(27, 14),"
                                                  "(28, 3),"
                                                  "(29, 21), "
                                                  "(30, 17),"
                                                  "(31, 34),"
                                                  "(32, 21),"
                                                  "(33, 17),"
                                                  "(34, 34),"
                                                  "(35, 20),"
                                                  "(36, 19),"
                                                  "(37, 35),"
                                                  "(38, 22),"
                                                  "(39, 18),"
                                                  "(40, 21),"
                                                  "(41, 18),"
                                                  "(42, 23),"
                                                  "(43, 23),"
                                                  "(44, 24),"
                                                  "(45, 25),"
                                                  "(46, 26),"
                                                  "(47, 27),"
                                                  "(48, 22),"
                                                  "(49, 28),"
                                                  "(50, 28),"
                                                  "(51, 31),"
                                                  "(52, 31),"
                                                  "(53, 27),"
                                                  "(54, 13),"
                                                  "(55, 23),"
                                                  "(56, 57),"
                                                  "(57, 58),"
                                                  "(58, 36),"
                                                  "(59, 37),"
                                                  "(60, 38),"
                                                  "(61, 38),"
                                                  "(62, 39),"
                                                  "(63, 40),"
                                                  "(64, 36),"
                                                  "(65, 36),"
                                                  "(66, 7),"
                                                  "(67, 6),"
                                                  "(68, 7),"
                                                  "(69, 43),"
                                                  "(70, 44),"
                                                  "(71, 7),"
                                                  "(72, 45),"
                                                  "(73, 46),"
                                                  "(74, 45),"
                                                  "(75, 47),"
                                                  "(76, 48),"
                                                  "(77, 49),"
                                                  "(78, 48),"
                                                  "(79, 49),"
                                                  "(80, 50),"
                                                  "(81, 51),"
                                                  "(82, 51),"
                                                  "(83, 52),"
                                                  "(84, 39),"
                                                  "(85, 51),"
                                                  "(86, 55),"
                                                  "(87, 45),"
                                                  "(88, 56),"
                                                  "(89, 43),"
                                                  "(90, 50)")


c.execute("""create table dept (Dept text)""")
c.execute("insert into dept Values ('CS')")


c.execute("""create table dept_course (name text references dept(Dept), course_number integer references course(CourseID))""")
c.execute("insert into dept_course Values ('CS', 1),"
                                         "('CS', 2),"
                                         "('CS', 3),"
                                         "('CS', 4),"
                                         "('CS', 5),"
                                         "('CS', 6),"
                                         "('CS', 7),"
                                         "('CS', 8),"
                                         "('CS', 9),"
                                         "('CS', 10),"
                                          "('CS', 11),"
                                          "('CS', 12),"
                                          "('CS', 13),"
                                          "('CS', 14),"
                                          "('CS', 15),"
                                          "('CS', 16),"
                                          "('CS', 17),"
                                          "('CS', 18),"
                                          "('CS', 19),"
                                          "('CS', 20),"
                                          "('CS', 21),"
                                          "('CS', 22),"
                                          "('CS', 23),"
                                          "('CS', 24),"
                                          "('CS', 25),"
                                          "('CS', 26),"
                                          "('CS', 27),"
                                          "('CS', 28),"
                                          "('CS', 29),"
                                          "('CS', 30),"
                                          "('CS', 31),"
                                          "('CS', 32),"
                                          "('CS', 33),"
                                          "('CS', 34),"
                                          "('CS', 35),"
                                          "('CS', 36),"
                                          "('CS', 37),"
                                          "('CS', 38),"
                                          "('CS', 39),"
                                          "('CS', 40),"
                                          "('CS', 41),"
                                          "('CS', 42),"
                                          "('CS', 43),"
                                          "('CS', 44),"
                                          "('CS', 45),"
                                          "('CS', 46),"
                                          "('CS', 47),"
                                          "('CS', 48),"
                                          "('CS', 49),"
                                          "('CS', 50),"
                                          "('CS', 51),"
                                          "('CS', 52),"
                                          "('CS', 53),"
                                          "('CS', 54),"
                                          "('CS', 55),"
                                          "('CS', 56),"
                                          "('CS', 57),"
                                          "('CS', 58),"
                                          "('CS', 59),"
                                          "('CS', 60),"
                                          "('CS', 61),"
                                          "('CS', 62),"
                                          "('CS', 63),"
                                          "('CS', 64),"
                                          "('CS', 65),"
                                          "('CS', 66),"
                                          "('CS', 67),"
                                          "('CS', 68),"
                                          "('CS', 69),"
                                          "('CS', 70),"
                                          "('CS', 71),"
                                          "('CS', 72),"
                                          "('CS', 73),"
                                          "('CS', 74),"
                                          "('CS', 75),"
                                          "('CS', 76),"
                                          "('CS', 77),"
                                          "('CS', 78),"
                                          "('CS', 79),"
                                          "('CS', 80),"
                                          "('CS', 81),"
                                          "('CS', 82),"
                                          "('CS', 83),"
                                          "('CS', 84),"
                                          "('CS', 85),"
                                          "('CS', 86),"
                                          "('CS', 87),"
                                          "('CS', 88),"
                                          "('CS', 89),"
                                          "('CS', 90)")


nums = [(1,3),(5,3),(4,8)]
c.execute("""create table ss (s1 integer PRIMARY KEY, s2 integer, s3 integer)""")
c.executemany("insert into ss (s2,s3) Values (?,?)",nums)
print(c.fetchall())


conn.commit()

conn.close()



